paths:
  /api/products/:
    get:
      description: Returns 204 without content
      operationId: products
      responses:
        "204":
          description: Service available
      summary: Check if the service is running.
      tags:
      - Get
      - all
swagger: "2.0"
host : "localhost:8090"
schemes:
  - https
  - http